server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/strike_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  jackson:
    time-zone: UTC

jwt:
  secret: STRIKE_SUPER_SECRET_KEY_2026_STRIKE_PLATFORM

services:
  vendor-url: http://localhost:8083
  card-url: http://localhost:8084
  redemption-url: http://localhost:8085
  ledger-url: http://localhost:8086