server:
  port: 8087

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://localhost:5432/strike_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  auth-url: http://localhost:8081
  user-url: http://localhost:8082
  vendor-url: http://localhost:8083
  card-url: http://localhost:8084
  redemption-url: http://localhost:8085
  ledger-url: http://localhost:8086
jwt:
  secret: STRIKE_SUPER_SECRET_KEY_2026_STRIKE_PLATFORM
