server:
  port: 8080

spring:
  application:
    name: strike-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders: "*"
                allowCredentials: false
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/user/**

            - id: vendor-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/vendor/**,/api/stores/**,/api/menu/**,/api/dashboard/**,/api/analytics/**

            - id: card-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/cards/**,/api/subscriptions/**

            - id: redemption-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/redemptions/**

            - id: ledger-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/ledger/**

            - id: admin-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/admin/**

jwt:
  secret: STRIKE_SUPER_SECRET_KEY_2026_STRIKE_PLATFORM